# Generated by Django 3.0.3 on 2020-02-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooli', '0002_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilepic',
            field=models.CharField(default='', max_length=255),
        ),
    ]
