# Generated by Django 3.0.3 on 2020-02-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hooli', '0004_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='main_color',
            new_name='main_colour',
        ),
    ]
