# Generated by Django 3.0.3 on 2020-03-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooli', '0005_auto_20200229_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.IntegerField()),
                ('liker', models.CharField(max_length=20)),
            ],
        ),
    ]
