# Generated by Django 3.0.3 on 2020-03-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hooli', '0007_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='Followers',
            new_name='follower',
        ),
    ]
