# Generated by Django 3.0.3 on 2020-03-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooli', '0008_auto_20200314_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoid', models.IntegerField()),
                ('coords', models.CharField(max_length=20)),
                ('tagged_user', models.CharField(default='', max_length=20)),
                ('tagged_by', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
